[package]
name = "bdip-cli"
version = "0.1.1"
edition = "2024"
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "High-performance command-line shader application for batch image processing using bdip-core."

[dependencies]
bdip-core = { path = "../bdip-core", version = "0.1.1" }
anyhow = "1"
clap = { version = "4.6.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.2.0"
image = "0.25.10"
tempfile = "3.27.0"
