[package]
name = "bdip-core"
version = "0.1.1"
edition = "2024"
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "High-performance, extensible shader library."

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
image = "0.25"
inventory = "0.3"
pollster = "0.4.0"
thiserror = "2"
wgpu = "29.0.1"
